"""Constrained Compound-REMI generation utilities.

Authorship note: this stabilization helper was generated by OpenAI Codex and
was intentionally separated from the Transformer-VAE implementation.

It constrains sampled fields by event family, forces structural metric events
when needed, advances positions monotonically within each bar, prevents empty
bars, and limits long event chains without a metric token.
"""

import torch


class CompoundREMIGenerationConstraints:
  def __init__(
    self,
    field2idx,
    token_attributes,
    batch_size,
    positions_per_bar,
    device,
    max_tokens_without_metric=24,
    temperature=0.9,
    top_k=8,
    min_velocity=6,
    min_duration=3
  ):
    self.field2idx = field2idx
    self.token_attributes = token_attributes
    self.batch_size = batch_size
    self.device = device
    self.max_tokens_without_metric = max_tokens_without_metric
    self.temperature = temperature
    self.top_k = top_k

    self.field_idx = {field: i for i, field in enumerate(token_attributes)}
    self.ignore_idx = {field: field2idx[field]["IGNORE"] for field in token_attributes}

    self.family_idx = self.field_idx["family"]
    self.bar_position_idx = self.field_idx["bar_position"]
    self.note_idx = field2idx["family"]["Note"]
    self.metric_idx = field2idx["family"]["Metric"]
    self.controller_idx = field2idx["family"]["Controller"]
    self.bar_idx = field2idx["bar_position"]["BAR"]
    self.zero_idx = field2idx["bar_position"]["0"]

    self.allowed_families = [self.note_idx, self.metric_idx, self.controller_idx]
    self.note_fields = {
      "channel": self._numeric_indices("channel", 0, 15),
      "program": self._numeric_indices("program", 0, 127),
      "pitch": self._numeric_indices("pitch", 0, 127),
      "velocity": self._numeric_indices("velocity", min_velocity),
      "duration": self._numeric_indices("duration", min_duration)
    }
    self.controller_fields = {
      "channel": self._numeric_indices("channel", 0, 15),
      "controller_type": self._numeric_indices("controller_type", 0, 127),
      "controller_value": self._numeric_indices("controller_value", 0, 127)
    }
    self.numeric_positions = {
      idx: int(token)
      for token, idx in field2idx["bar_position"].items()
      if token.isdigit() and int(token) < positions_per_bar
    }
    self.tempo_indices = [field2idx["tempo"]["CONTINUE"], *self._float_indices("tempo")]

    self.force_bar = torch.ones(batch_size, dtype=torch.bool, device=device)
    self.need_position_zero = torch.zeros(batch_size, dtype=torch.bool, device=device)
    self.current_position = torch.full((batch_size,), -1, dtype=torch.long, device=device)
    self.tokens_since_metric = torch.zeros(batch_size, dtype=torch.long, device=device)
    self.events_since_bar = torch.zeros(batch_size, dtype=torch.long, device=device)

  def _numeric_indices(self, field, minimum=None, maximum=None):
    valid_indices = []

    for token, idx in self.field2idx[field].items():
      try:
        value = int(token)
      except ValueError:
        continue

      if minimum is not None and value < minimum:
        continue
      if maximum is not None and value > maximum:
        continue

      valid_indices.append(idx)

    return valid_indices

  def _float_indices(self, field):
    valid_indices = []

    for token, idx in self.field2idx[field].items():
      try:
        float(token)
        valid_indices.append(idx)
      except ValueError:
        pass

    return valid_indices

  def _sample(self, field_logits, allowed_indices):
    if len(allowed_indices) == 0:
      raise ValueError("No valid tokens are available for this field.")

    field_logits = field_logits.clone().float() / self.temperature
    invalid_mask = torch.ones(
      field_logits.size(-1),
      dtype=torch.bool,
      device=field_logits.device
    )
    invalid_mask[allowed_indices] = False
    field_logits[:, invalid_mask] = -torch.inf

    if self.top_k is not None and self.top_k > 0:
      k = min(self.top_k, len(allowed_indices))
      top_values = torch.topk(field_logits, k=k, dim=-1).values
      cutoff = top_values[:, -1].unsqueeze(-1)
      field_logits[field_logits < cutoff] = -torch.inf

    probabilities = torch.softmax(field_logits, dim=-1)
    if not torch.isfinite(probabilities).all():
      raise FloatingPointError("Non-finite generation probabilities.")

    return torch.multinomial(probabilities, num_samples=1)

  def sample_next(self, logits):
    predictions = torch.empty(
      self.batch_size,
      1,
      len(self.token_attributes),
      dtype=torch.long,
      device=self.device
    )

    for field in self.token_attributes:
      predictions[:, 0, self.field_idx[field]] = self.ignore_idx[field]

    force_metric = (
      self.force_bar
      | self.need_position_zero
      | (self.tokens_since_metric >= self.max_tokens_without_metric)
    )
    free_rows = ~force_metric

    if free_rows.any():
      predictions[free_rows, 0, self.family_idx] = self._sample(
        logits["family"][free_rows, -1, :],
        self.allowed_families
      )[:, 0]

    predictions[force_metric, 0, self.family_idx] = self.metric_idx
    is_note = predictions[:, 0, self.family_idx] == self.note_idx
    is_metric = predictions[:, 0, self.family_idx] == self.metric_idx
    is_controller = predictions[:, 0, self.family_idx] == self.controller_idx

    note_rows = torch.where(is_note)[0]
    for field, allowed_indices in self.note_fields.items():
      if len(note_rows) > 0:
        predictions[note_rows, 0, self.field_idx[field]] = self._sample(
          logits[field][note_rows, -1, :],
          allowed_indices
        )[:, 0]

    controller_rows = torch.where(is_controller)[0]
    for field, allowed_indices in self.controller_fields.items():
      if len(controller_rows) > 0:
        predictions[controller_rows, 0, self.field_idx[field]] = self._sample(
          logits[field][controller_rows, -1, :],
          allowed_indices
        )[:, 0]

    metric_rows = torch.where(is_metric)[0]
    for row_tensor in metric_rows:
      row = row_tensor.item()

      if self.force_bar[row]:
        allowed_positions = [self.bar_idx]
      elif self.need_position_zero[row]:
        allowed_positions = [self.zero_idx]
      else:
        later_positions = [
          idx
          for idx, position in self.numeric_positions.items()
          if position > self.current_position[row].item()
        ]
        allow_bar = self.events_since_bar[row].item() > 0 or len(later_positions) == 0
        allowed_positions = later_positions + ([self.bar_idx] if allow_bar else [])

      predictions[row, 0, self.bar_position_idx] = self._sample(
        logits["bar_position"][row:row + 1, -1, :],
        allowed_positions
      )[0, 0]

    is_bar = is_metric & (predictions[:, 0, self.bar_position_idx] == self.bar_idx)
    metric_position = is_metric & ~is_bar
    bar_rows = torch.where(is_bar)[0]
    metric_position_rows = torch.where(metric_position)[0]

    if len(bar_rows) > 0:
      predictions[bar_rows, 0, self.field_idx["time_signature"]] = self.field2idx[
        "time_signature"
      ]["CONTINUE"]

    if len(metric_position_rows) > 0:
      predictions[metric_position_rows, 0, self.field_idx["tempo"]] = self._sample(
        logits["tempo"][metric_position_rows, -1, :],
        self.tempo_indices
      )[:, 0]
      predictions[metric_position_rows, 0, self.field_idx["time_signature"]] = self.field2idx[
        "time_signature"
      ]["CONTINUE"]

    for row_tensor in metric_position_rows:
      row = row_tensor.item()
      position_idx = predictions[row, 0, self.bar_position_idx].item()
      self.current_position[row] = self.numeric_positions[position_idx]

    self.current_position[is_bar] = -1
    self.events_since_bar = torch.where(
      is_bar,
      torch.zeros_like(self.events_since_bar),
      self.events_since_bar
    )
    self.events_since_bar += (is_note | is_controller).long()
    self.need_position_zero = is_bar
    self.force_bar.zero_()
    self.tokens_since_metric = torch.where(
      is_metric,
      torch.zeros_like(self.tokens_since_metric),
      self.tokens_since_metric + 1
    )

    return predictions, is_bar


def generate_constrained_tokens(
  model,
  prompt,
  latent_provider,
  generation_length,
  sequence_length,
  constraints,
  idx2field,
  progress=lambda values: values
):
  """Decode tokens while delegating structural stability to ``constraints``."""
  x = prompt.repeat(constraints.batch_size, 1, 1)
  generated_tokens = [[] for _ in range(constraints.batch_size)]
  bars_generated = torch.zeros(
    constraints.batch_size,
    dtype=torch.long,
    device=constraints.device
  )

  for _ in progress(range(generation_length)):
    z = latent_provider(bars_generated)
    logits = model.decode(x[:, -sequence_length:], z)
    predictions, is_bar = constraints.sample_next(logits)
    bars_generated += is_bar.long()
    x = torch.cat((x, predictions), dim=1)

    for sample_idx in range(constraints.batch_size):
      generated_tokens[sample_idx].append(
        " ".join(
          idx2field[field][predictions[sample_idx, 0, field_number].item()]
          for field_number, field in enumerate(constraints.token_attributes)
        )
      )

  return generated_tokens